name: Backup Codespace

on:
  push:
    branches:
      - main

  workflow_dispatch:  # Permite ejecución manual

  schedule:
    - cron: '*/10 * * * *'  # Ejecuta cada 10 minutos

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout el repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Crear carpeta de respaldo
        run: |
          mkdir -p /tmp/backup_codespace
          rsync -av --progress . /tmp/backup_codespace --exclude .git --exclude /tmp

      - name: Inicializar nuevo repositorio de respaldo
        run: |
          cd /tmp/backup_codespace
          git init
          git remote add origin https://github.com/FrankRespaldos/RespaldoLosgrandesmatis.git
          git add .
          git commit -m "Backup automático del Codespace"
          git branch -M main

      - name: Subir cambios al repositorio de respaldo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /tmp/backup_codespace
          git push --force origin main
