name: Backup Entire Codespace

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # Se ejecuta cada 10 minutos automáticamente
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Backup Repo
        uses: actions/checkout@v3
        with:
          repository: FrankRespaldos/RespaldoLosgrandesmatis
          token: ${{ secrets.BACKUP_GITHUB_TOKEN }}

      - name: Listar archivos del Codespace (Debug)
        run: ls -la ${{ github.workspace }}

      - name: Copiar todo el Codespace al Repositorio de Respaldo
        run: |
          git config user.name "FrankRespaldos"
          git config user.email "frankmulloni2@gmail.com"

          # Copia TODO el contenido del Codespace excepto carpetas innecesarias
          rsync -av --exclude=.git --exclude=.github $GITHUB_WORKSPACE/ .

          git add .
          git commit -m "Backup de todo el Codespace" || echo "No changes to commit"
          git push --force origin main
