name: Backup Codespace

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'  # Cada 10 minutos
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout el repositorio
        uses: actions/checkout@v3

      - name: Verificar contenido del Codespace
        run: ls -la ${{ github.workspace }}

      - name: Preparar carpeta de respaldo
        run: |
          echo "Creando carpeta de respaldo..."
          mkdir -p /tmp/backup_codespace
          rsync -av --exclude='/tmp/backup_codespace' ${{ github.workspace }}/ /tmp/backup_codespace/

      - name: Subir respaldo al repositorio
        run: |
          cd /tmp/backup_codespace

          # Configurar git
          git init
          git config user.name "FrankRespaldos"
          git config user.email "frankmulloni2@gmail.com"
          git branch -M main
          
          # Eliminar remote si ya existe para evitar errores
          git remote remove origin || echo "No remote to remove"

          git remote add origin https://x-access-token:${{ secrets.BACKUP_GITHUB_TOKEN }}@github.com/FrankRespaldos/RespaldoLosgrandesmatis.git
          git pull origin main || echo "No previous repo found"

          # Agregar y hacer commit de los archivos
          git add .
          git commit -m "Backup del Codespace" || echo "No changes to commit"
          git push --force origin main
