name: Backup Codespace

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar todos los días a medianoche (opcional)
  push:
    branches:
      - main # Ejecutar cuando haya cambios en main
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub Actions

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar Git
        run: |
          git config --global user.name "FrankRespaldos"
          git config --global user.email "frankmulloni2@gmail.com"

      - name: Clonar el Codespace
        run: |
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/codespaces/studious-system-pj74wv4xxjr9hj9x.git /tmp/backup_codespace

      - name: Subir respaldo al repositorio de respaldo
        run: |
          cd /tmp/backup_codespace
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/FrankRespaldos/RespaldoLosgrandesmatis.git
          git branch -M main
          git add .
          git commit -m "Respaldo automático del Codespace $(date +'%Y-%m-%d %H:%M:%S')"
          git push -u origin main
