name: Backup Codespace

on:
  schedule:
    - cron: '0 0 * * *'  # Corre una vez al día a la medianoche UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el Codespace
        run: |
          git clone https://USERNAME:TOKEN@github.com/codespaces/studious-system-pj74wv4xxjr9hj9x /tmp/backup_codespace
        env:
          USERNAME: Fraankconuuntain
          TOKEN: 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  # <-- Reemplaza con tu Personal Access Token (PAT)

      - name: Configurar Git
        run: |
          git config --global user.email "frankmulloni2@gmail.com"
          git config --global user.name "FrankRespaldos"

      - name: Inicializar el repositorio de respaldo
        run: |
          cd /tmp
          git clone https://FrankRespaldos:TOKEN@github.com/FrankRespaldos/RespaldoLosgrandesmatis.git backup_repo
        env:
          TOKEN: TU_TOKEN_AQUI  # <-- Reemplaza con tu Personal Access Token (PAT)

      - name: Copiar los archivos al repositorio de respaldo
        run: |
          cp -r /tmp/backup_codespace/* /tmp/backup_repo/
          cd /tmp/backup_repo
          git add .
          git commit -m "Backup Codespace - $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
