Run cd /tmp/backup_codespace
Reinitialized existing Git repository in /tmp/backup_codespace/.git/
From https://github.com/FrankRespaldos/RespaldoLosgrandesmatis
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint:
hint:   git config pull.rebase false  # merge
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
No previous repo found
On branch main
nothing to commit, working tree clean
No changes to commit
remote: Permission to FrankRespaldos/RespaldoLosgrandesmatis.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/FrankRespaldos/RespaldoLosgrandesmatis.git/': The requested URL returned error: 403
Error: Process completed with exit code 128.
