name: Backup Codespace

on:
  schedule:
    - cron: '0 0 * * *'  # Corre todos los días a medianoche UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecución manual

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio original
        uses: actions/checkout@v3
        with:
          repository: Fraankconuuntain/LOSGRANDESMATIS-
          token: ${{ secrets.PAT_TOKEN }}

      - name: Crear carpeta de respaldo
        run: |
          mkdir -p /tmp/backup_codespace
          cp -r . /tmp/backup_codespace/

      - name: Inicializar Git en la carpeta de respaldo
        run: |
          cd /tmp/backup_codespace
          git init
          git remote add origin https://github.com/FrankRespaldos/RespaldoLosgrandesmatis.git
          git config user.name "FrankRespaldos"
          git config user.email "frankmulloni2@gmail.com"

      - name: Subir respaldo al repositorio de respaldo
        run: |
          cd /tmp/backup_codespace
          git add .
          git commit -m "Backup del Codespace - $(date +'%Y-%m-%d %H:%M:%S')"
          git branch -M main
          git push -f https://FrankRespaldos:${{ secrets.PAT_TOKEN }}@github.com/FrankRespaldos/RespaldoLosgrandesmatis.git main
